apiVersion: apps/v1
kind: Deployment
metadata:
  name: kerberos
  namespace: kerberos
spec:
  selector:
    matchLabels:
      app: kerberos
  replicas: 1
  template:
    metadata:
      name: kerberos
      labels:
        app: kerberos
    spec:
      containers:
      - name: kerberos
        image: kerberos/kerberos
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: kerberos-node-port
  namespace: kerberos
spec:
  type: NodePort
  selector:
    app: kerberos
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: livestream
    port: 8889
    targetPort: 8889
    nodePort: 30889



